### ISSUE TITLE
extobjc headers conflict with ReactiveCocoa 3.0-RC1

### ISSUE THREAD

**Issue by gonzalezreal** [Mantle/Mantle#570] opened 2015-07-31 11:51 UTC
When installing Mantle 2.0 and ReactiveCocoa 3.0-RC1 via cocoapods there is a conflict when importing `EXTRuntimeExtensions.h` in the source code. Xcode is using Mantle's version of this header, which uses the `mtl_` prefix and thus ReactiveCocoa does not compile.

I think this could be fixed by using different header names on each project.

Any ideas in how to fix it?

**Comment by robb** [comment] 2015-07-31 12:09
Could this be a duplicate of #377?

**Comment by gonzalezreal** [comment] 2015-07-31 13:02
Yes, it is basically the same problem, sorry for the dup.

I am not sure what Cocoapods is doing, but the result is that ReactiveCocoa ends importing the Mantle version of `EXTRuntimeExtensions.h`.

**Closed** 2015-08-01 12:28 UTC
