### ISSUE TITLE
subclass can't  map the parent's keys

### ISSUE THREAD

**Issue by walkerwzy** [Mantle/Mantle#693] opened 2016-04-21 13:41 UTC
example: 
```
@interface obja : MTLModel<MTLJSONSerializing>
@property (nonatomic, copy) NSString *firstname;
@end

@implementation obja
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{@"firstname": @"firstname"};
}
@end

@interface objb : obja
@property (nonatomic, copy) NSString *lastname;
@end

@implementation objb
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{@"lastname": @"lastname"};
}
@end
```

run the test:
```
    NSDictionary *dict = @{
                           @"firstname": @"walker",
                           @"lastname": @"wang"
                           };
    objb *o = (objb *)[MTLJSONAdapter modelOfClass:[objb class] fromJSONDictionary:dict error:nil];
    NSLog(@"%@", o);
```

output:
```
2016-04-21 21:40:41.368 xxxxx[16287:4305890] <objb: 0x7f8d12024c40> {
    firstname = "<null>";
    lastname = wang;
}
```

**Comment by JanGorman** [comment] 2016-04-21 13:58
There's no implicit mapping of values in Mantle, you always need to tell each class which values to map. In your case your `objb` implementation would need to look more like this. There's a `mtl_dictionaryByAddingEntriesFromDictionary` method for that purpose.

```objective-c
@implementation objb
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
  NSDictionary *mapping = @{
    @"lastname": @"lastname"
   };
  return [[super JSONKeyPathsByPropertyKey] mtl_dictionaryByAddingEntriesFromDictionary:mapping];
}
@end
```

**Comment by walkerwzy** [comment] 2016-04-21 14:01
yes, I'm just writing my own category to merge the two. seems it's the only way now.

**Comment by JanGorman** [comment] 2016-04-21 14:03
It's like that by design. I'm closing the issue.

**Closed by JanGorman** 2016-04-21 14:03 UTC

**Comment by walkerwzy** [comment] 2016-04-21 14:24
here's new thing:
I create a framework for others to use, so such code above is in framework, and only export `.h` file, 
then in real project, when we wrote `[super JSONKeyPathsByPropertyKey]`, an error occur:
`no known class method for selector "JSONKeyPathsByPropertyKey"`

yes, it's written in the `.m` file, we surely can't know that, so how to fix that? how to merge all fields with the super class?

**Comment by dcaunt** [comment] 2016-04-21 14:53
You could check if the superclass conforms to the `MTLJSONSerializing` protocol, where `+JSONKeyPathsByPropertyKey` is a required method.

**Comment by walkerwzy** [comment] 2016-04-21 16:54
it's odd thing.
my architect is this:
a base model inherit `MTLModel`, and conforms `MTLJSONSerializing`
a wrap model inherit the base model, let's say `ModelB`

in my framework and  it's unit test , any model inherit `ModleB`, all success.
then I export to another project as a framework, it show can't find that class method.

okay, I explicit declare ModelB as: `@interface ModelB : ModelA<MTLJSONSerializing>`
it can find that method, but another error shows:
`Declaration of 'MTLJSONSerializing' must be imported from module 'PMRESTLib' before it is required`
i can't figure out why, and add `<Mantle/JSONAdapter>` many place to try, still not work
