### ISSUE TITLE
A problem when I try to solve JSON data with a nesting array.

### ISSUE THREAD

**Issue by sunwell** [Mantle/Mantle#757] opened 2016-10-10 14:45 UTC
My two models like below:

```
@interface SSA : MTLModel <MTLJSONSerializing>
@property (nonatomic) NSString *ssPaperId;
@property (nonatomic) NSString *ssPicture;
@property (nonatomic) NSString *ssTitle;
@property (nonatomic) NSString *ssPrice;
@property (nonatomic) NSString *ssSpiderPrice;
@property (nonatomic) NSString *ssPeriod;
@property (nonatomic) NSString *ssPricePeriod;
@property (nonatomic) BOOL ssGiftFlag;
@property (nonatomic) NSArray *ssGifts;
@end

@interface SSB : MTLModel <MTLJSONSerializing>
@property (nonatomic) NSString *ssGiftTitle;
@property (nonatomic) NSString *ssGiftPicture;
@property (nonatomic) NSString *ssGiftType;
@end
```
And `SSA` correspond to a element of papers, `SSB` correspond to a element of `gifts`, and in model `SSA`, the array property `ssGifts` is an array of `SSB`.

And in `SSA.m,` I have three methods below:

```
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{@"ssPaperId":@"paperId",
             @"ssPicture":@"pictue",
             @"ssTitle":@"title",
             @"ssPrice":@"price",
             @"ssSpiderPrice":@"spiderPrice",
             @"ssPeriod":@"period",
             @"ssPricePeriod":@"pricePeriod",
             @"ssGiftFlag":@"giftflag",
             @"ssGifts":@"gifts"};
}

+ (NSValueTransformer *)ssGiftFlagJSONTransformer {
    return [NSValueTransformer valueTransformerForName:MTLBooleanValueTransformerName];
}

+ (NSValueTransformer *)ssGiftsJSONTransformer {
    return [MTLValueTransformer transformerUsingForwardBlock:^id(NSArray *gifts, BOOL *success, NSError *__autoreleasing *error) {
        NSError *err = nil;
        return [MTLJSONAdapter modelsOfClass:SSB.class fromJSONArray:gifts error:&err];
    }];
}

```

But when I try to resolve JSON data, the whole array of `SSA` is nil.

[Here is the JSON data](http://m.spider.com.cn/app20/getGiftList.action?key=spidersubscriber&sign=9B41B7A2C97B2E300B927AE6183F0712&fileType=json&platformId=1&itemId=100032,100046,100047,100131,100037,100029&count=10&page=1)

**Comment by dcaunt** [comment] 2016-10-11 10:20
I suspect the problem is that giftflag is a string `"y"` in your JSON. You would need to return a custom transformer in `ssGiftFlagJSONTransformer` which returns `@YES` or `@NO` depending on whether the string is equal to `"y"` or not.

If it still isn't working, can you add the implementation of `SSB.m` and also post the code you use to actually transform the JSON data to an array of `SSA` models please?

**Comment by sunwell** [comment] 2016-10-11 13:20
@dcaunt  Yes, you are right. Thx.

**Comment by dcaunt** [comment] 2016-10-11 13:32
👍 closing this for now then.

**Closed by dcaunt** 2016-10-11 13:32 UTC
Labels: JSON, question
